matrix:
  include:
    - language: node_js
      node_js:
        - node
      before_script:
        - cd frontend

    - language: java
      jdk: openjdk8
      before_script:
        - cd send-emails

    - language: java
      jdk: openjdk11
      before_script:
        - cd server
