matrix:
  include:
    - language: node_js
      node_js:
        - node
      before_script:
        - cd frontend
      script:
        - npm run test

    - language: java
      jdk: oraclejdk8
      before_script:
        - cd send-emails

    - language: java
      jdk: oraclejdk11
      before_script:
        - cd server
