matrix:
  include:
    - language: node_js
      node_js:
        - node
      cache:
        directories:
          - "frontend/node_modules"
      before_script:
        - cd frontend
        - npm install

    - language: java
      jdk: openjdk8
      before_script:
        - cd send-emails

    - language: java
      jdk: openjdk11
      before_script:
        - cd server
