matrix:
  include:
  - language: node_js
    node_js:
    - node
    cache:
      directories:
      - frontend/node_modules
    before_script:
    - cd frontend
    - npm install
    before_deploy: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAWPLC2AJPVKVCUBV3
      secret_access_key:
             secure: d0wYdRvHLhIzwLzsr+KkVVE26wUj19NbhsAT97NW8x+aOTuJBnrex7Eb5wTU8CfvB11JEJ6qDqBtwzVUfs390FiofGHs2CR1KSPHx4pkVckU04FRy+UwpZj8D4J6i5BLmllL2iSt/g8eZthsaezwube4gAQDZUnN27e52QsjSjqFzDbL0rCTPzHc/z7BVRXI8nqll9nxSrzGh2mkC3SVU0SIamo7Kj8QDl2OZMgB/BHlvh5o0uxSohtLLF2Y+oN3OlOqSRSt5tvH+F4Q2gyhYbiCYwbLbFCE1aXamf2b7bQ+9kuMaefrhFKtauDYQFgUxWOWbHoRYoyZQgp0i3oTGfKDHtCmwQFnseWqI5K0xx4UrOHgnR6J3Rp1v9eyNvYcwjUIqd8P5QXCHaVI2fHlefHhS4sVXOrBwpZsGP7LAypXvxPQJ1YmcoWEPsn3sbYK4aRq7rIPD5FPH/h5MlGP4EHGmxfT3fGkVXxoNBtLOpAByadewmiVlC8vTXqltfGXHK5CCR5nVkNNWIYeTdMBxmHpAN0T86Q+L6lDPajIHcsUOhR6S1pwLtMJ9np6ze6WuNDNMyrGXEIPKNlsXdmzKsZKAotyN45bw9N2oS8Y+CAylbHpvfvLzzytSbJup7m0AZqkEG7xBsPWDPpCibFzkOTIUTfXCvYBtLivIzXdV8o=
      bucket: pulsesurveys
      local-dir: build
      acl: public_read
      skip_cleanup: true
      region: us-east-2
  - language: java
    jdk: openjdk8
    before_script:
    - cd send-emails
  - language: java
    jdk: openjdk11
    before_script:
    - cd server


